### PR TITLE
docs: add how-to for internal TLS

### PR DESCRIPTION
**Pull request by WanzenBug**
Add a how-to for setting up internal TLS, both with cert-manager and manually, using openssl.

### CODE REVIEW

**Comment by WanzenBug** [comment]
Tried my hand at a first "how-to". Still a draft, because I haven't actually verified that the instructions are working, especially the manual TLS steps.

**Review by JoelColledge — COMMENTED** [review]
Looks great! Reads as I would expect a how-to to.

**Comment by WanzenBug** [comment]
Perhaps surprisingly, the instructions worked almost flawlessly. Only needed to add some namespace and other metadata.

**Review by JoelColledge — APPROVED** [review]

**Comment by JoelColledge** [comment]
We should refer to this from somewhere so that users can find it.

**Review by JoelColledge — APPROVED** [review]

**Pull request merged**
