### PR TITLE
Update kube-api resources to v1.21

### PR DESCRIPTION
**Pull request by WanzenBug**
Updates the client components to kubernetes release 1.21. This requires
some shuffling of interfaces to satisfy some changed signatures, as well
as some new RBAC resources.

Signed-off-by: Moritz "WanzenBug" Wanzenböck <moritz.wanzenboeck@linbit.com>

### CODE REVIEW

**Comment by WanzenBug** [comment]
Draft for now, need to find the time to test different kubernetes versions

**Comment by JoelColledge** [comment]
Is this intentionally still a draft?

**Comment by WanzenBug** [comment]
Yeah, haven't gotten around to checking with Kubernetes v1.19 or even older.

**Comment by WanzenBug** [comment]
Works with v1.18, which is already EOL, should be fine to update.

**Review by JoelColledge — APPROVED** [review]
Looks good to me! I was entertained by the `yes` var :smile:

**Pull request merged**
