### PR TITLE
Update CSI images

### PR DESCRIPTION
**Pull request by kvaps**
The CSI images updated to latest versions

### CODE REVIEW

**Review by WanzenBug — DISMISSED** [review]
I'll need to do some tests, see if additional rules for RBAC are required, but in general: LGTM.

Please "sign-off" as required by the CNCF/DOC bot.

EDIT: and also run `make deploy/piraeus` to generate example deployment.

**Review by WanzenBug — APPROVED** [review]

**Comment by WanzenBug** [comment]
@kvaps I notice some issues related to #260, i.e. the attacher image also wants a `-worker-threads` option instead of `-workers`.

Also, one thing I didn't think about was that the changes in the CRDs break backwards compatibility, i.e. when upgrading you need to manually replace the CRDs first.

I'd push some fixes for both issues on this branch, if you don't mind?

**Comment by kvaps** [comment]
Yeah you're right. Sure, no objections.

**Comment by WanzenBug** [comment]
Finally managed to e2e test it. LGTM

**Pull request merged**
