### PR TITLE
Added selinux options

### PR DESCRIPTION
**Pull request by duckhawk**
Added SELinux options for enforced mode

Without this kernel module injector can't work with enforced SELinux mode.

Also, there is linked changes in drbd
https://lists.linbit.com/pipermail/drbd-dev/2023-May/007050.html

### CODE REVIEW

**Comment by duckhawk** [comment]
> From my futher tests, this also needs to set the following environment: `LB_SELINUX_AS=modules_object_t`
> 
> Please rebase and add that.

Added and rebased

**Review by WanzenBug — APPROVED** [review]

**Comment by duckhawk** [comment]
@WanzenBug sorry, somehow one parameter from master in values.yaml was missed. Fixed it.

**Review by WanzenBug — DISMISSED** [review]

**Comment by WanzenBug** [comment]
Looks like you need to run `make helm-values deploy/piraeus` once.

**Comment by duckhawk** [comment]
> Looks like you need to run `make helm-values deploy/piraeus` once.

Commited yaml changes, that appeared after this command execution

**Review by WanzenBug — APPROVED** [review]

**Comment by WanzenBug** [comment]
Thanks!

**Pull request merged**
