### PR TITLE
Replace STORK with linstor-scheduler-extender

### PR DESCRIPTION
**Pull request by kvaps**
fixes https://github.com/piraeusdatastore/piraeus-operator/issues/270

I just imported the code from our project and adapted it for piraeus-operator chart.
https://github.com/deckhouse/deckhouse/pull/746

Unfortunately I have no cluster to test that now. Feel free to push any changes here.

### CODE REVIEW

**Comment by WanzenBug** [comment]
This seems to me like something we could add to https://github.com/piraeusdatastore/helm-charts instead of here, and just add a (optional) dependency to the operator chart. I believe it would be easier to track any changes required by new kubernetes versions (as we need to update the scheduler config) from a standalone repository.

**Comment by WanzenBug** [comment]
Closing this, as we have https://artifacthub.io/packages/helm/piraeus-charts/linstor-scheduler

**Comment by kvaps** [comment]
Shouldn't we update the [docs.linbit.com](https://docs.linbit.com/).
Users still trying to use stork for that.

**Comment by WanzenBug** [comment]
Sure, will see about getting that updated.

**Pull request closed without merging**
